AWSTemplateFormatVersion: 2010-09-09
Description: >
  1. https://api.slack.com/apps > Create a Slack application >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  2. Slack App > Bot Users > Create Bot User >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  3. Slack App > OAuth & Permissions > Scopes > bot, chat:write:bot, chat:write:user, files:write:user >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  4. Slack > Add the Bot User to your channel >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  5. This Stack > Leave empty values if you don't intend to use a function > Create Stack >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  6. After creating this Stack > Slack App > Interactive Components > On > Set Request URL to this template's API Gateway Endpoint URL >>>>>>>>>>>

Parameters:
  # 7. Add the following lines to the post_build of your CodeBuild project:
  # - touch metadata.nfo
  # # Replace METADATA_BUCKET_NAME with YOUR Metadata Bucket Name
  # - aws s3 cp metadata.nfo s3://METADATA_BUCKET_NAME/metadata.nfo --metadata source_id=${CODEBUILD_RESOLVED_SOURCE_VERSION},webhook_base_ref=${CODEBUILD_WEBHOOK_BASE_REF},webhook_head_ref=${CODEBUILD_WEBHOOK_HEAD_REF},webhook_event=${CODEBUILD_WEBHOOK_EVENT},webhook_actor=${CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID},webhook_trigger=${CODEBUILD_WEBHOOK_TRIGGER},repo_url=${CODEBUILD_SOURCE_REPO_URL}
  Stage:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "staging"
      - "prod"
  AppName:
    Type: String
    Default: "my-app"
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  SlackAuthBotAccessToken:
    Type: String
    NoEcho: True
    Default: ""
    Description: "https://api.slack.com/apps > Slack App > OAuth & Permissions > Bot User OAuth Access Token"
  SlackAuthSigningSecret:
    Type: String
    NoEcho: True
    Default: ""
    Description: "https://api.slack.com/apps > Slack App > Basic Information > Signing Secret > Show"
  SlackChannel:
    Type: String
    Default: "MyAppNotifications"
    AllowedPattern: ^[a-zA-Z0-9]*$
  CodePipelineName:
    Type: String
    Default: "my-app-codepipeline"
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  # GitHubRepoName:
  #   Type: String
  # GitHubOwner:
  #   Type: String
  # GitHubBranch:
  #   Type: String
  MetadataBucketName:
    Type: String
    Default: "my-app-metadata-bucket"
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  MetadataFileName:
    Type: String
    Default: "metadata.nfo"
  MetadataCreateBucket:
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"
  SlackPostBuildStatusCodeBuildProjectName:
    Type: String
    Default: "my-app-codebuild"
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  CodepipelineAutoConditionBucketName:
    Type: String
    Default: "my-app-qa-results-bucket"
    Description: "Bucket name of the file to check"
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  CodepipelineAutoConditionFileName:
    Type: String
    Default: "qa-results.html"
    Description: "File name to check"
  CodepipelineAutoConditionMetadataProperty:
    Type: String
    Default: "qa-results.html"
    Description: "Metadata property to check"
  CodepipelineAutoConditionMetadataSuccess:
    Type: String
    Default: "qa_success"
    Description: "Auto approve if metadata property value equals to this value, otherwise auto reject"
  SlackPostApprovalRequestReleaseSnsTopicName:
    Type: String
    Default: "Release"
    Description: "Subscribe the function to this SNS topic"
  # CodepipelineAutoConditionRejectedBucketName:
  #   Type: String
  #   Default: ""
  # CodepipelineAutoConditionRejectedFileName:
  #   Type: String
  #   Default: ""
  # CodepipelineAutoConditionUploadBucketName:
  #   Type: String
  #   Default: ""
  # CodepipelineAutoConditionUploadFileName:
  #   Type: String
  #   Default: ""
  # CodepipelineAutoConditionUploadMessage:
  #   Type: String
  #   Default: ""
  CopyObjectOutputBucketName:
    Type: String
    Default: "my-app-testedcandidates-bucket"
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  CopyObjectOutputFileName:
    Type: String
    Default: "testedcandidate.zip"
  CopyObjectSourceBucketName:
    Type: String
    Description: "If empty, will attempt to copy CodePipeline artifact"
    Default: "my-app-candidates-bucket"
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  CopyObjectSourceSourceFileName:
    Description: "If empty, will attempt to copy CodePipeline artifact"
    Type: String
    Default: "candidate.zip"
  SlackPostApprovalRequestFinalSnsTopicName:
    Type: String
    Description: "Subscribe the function to this SNS topic"
    Default: "Final"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "App Details"
        Parameters:
          - AppName
          - Stage
          - CodePipelineName
      - Label:
          default: "Metadata File Details"
        Parameters:
          - MetadataCreateBucket
          - MetadataBucketName
          - MetadataFileName
      - Label:
          default: "Slack Details"
        Parameters:
          - SlackChannel
          - SlackAuthSigningSecret
          - SlackAuthBotAccessToken
      - Label:
          default: "1: Slack - Post CodeBuild Status to channel"
        Parameters:
          # - SlackPostBuildStatusTemplatePath # TODO- hardcode
          - SlackPostBuildStatusCodeBuildProjectName
      - Label:
          default: "2: Codepipeline - Auto Approve Conditionally"
        Parameters:
          - CodepipelineAutoConditionBucketName
          - CodepipelineAutoConditionFileName
          - CodepipelineAutoConditionMetadataProperty
          - CodepipelineAutoConditionMetadataSuccess
          # - CodepipelineAutoConditionRejectedBucketName # optional
          # - CodepipelineAutoConditionRejectedFileName # optional
          # - CodepipelineAutoConditionUploadBucketName # optional
          # - CodepipelineAutoConditionUploadFileName # optional
          # - CodepipelineAutoConditionUploadMessage # optional
      - Label:
          default: "3: Slack - Post Approval request to channel"
        Parameters:
          # - SlackPostApprovalRequestReleaseMetadataBucketName
          # - SlackPostApprovalRequestReleaseMetadataFileName
          # - SlackPostApprovalRequestReleaseTemplatePath # TODO- hardcode
          - SlackPostApprovalRequestReleaseSnsTopicName # TODO: dynamic in custom.yml
          # - SlackPostApprovalRequestReleaseRejectedBucketName # optional
          # - SlackPostApprovalRequestReleaseRejectedFileName # optional
          # hardcode Invoke lambda function name
          # slack update release
      - Label:
          default: "4: Lambda - Copy object"
        Parameters:
          - CopyObjectSourceBucketName # if empty, uses artifacts from codepipeline
          - CopyObjectSourceSourceFileName # if empty, uses artifacts from codepipeline
          - CopyObjectOutputBucketName
          - CopyObjectOutputFileName
      - Label:
          default: "5: Slack - Post Approval request to channel"
        Parameters:
          # - SlackPostApprovalRequestFinalMetadataBucketName
          # - SlackPostApprovalRequestFinalMetadataFileName
          # - SlackPostApprovalRequestFinalTemplatePath # TODO- hardcode
          - SlackPostApprovalRequestFinalSnsTopicName # TODO: dynamic in custom.yml
          # - SlackPostApprovalRequestFinalRejectedBucketName # optional
          # - SlackPostApprovalRequestFinalRejectedFileName # optional
    ParameterLabels:
      Stage:
        default: "Stage / Environment"
      AppName:
        default: "Application Name"
      SlackAuthBotAccessToken:
        default: "Slack App Bot Access Token (Hidden)"
      SlackAuthSigningSecret:
        default: "Slack App Signing Secret (Hidden)"
      SlackChannel:
        default: "Slack Channel"
      CodePipelineName:
        default: "CodePipeline Name"
      MetadataBucketName:
        default: "Metadata Bucket Name"
      MetadataFileName:
        default: "Metadata File Name"
      MetadataCreateBucket:
        default: "Create Metadata Bucket?"
      SlackPostBuildStatusCodeBuildProjectName:
        default: "CodeBuild Project Name"
      CodepipelineAutoConditionBucketName:
        default: "Condition Bucket Name"
      CodepipelineAutoConditionFileName:
        default: "Condition File Name"
      CodepipelineAutoConditionMetadataProperty:
        default: "Condition Metadata Property"
      CodepipelineAutoConditionMetadataSuccess:
        default: "Condition Metadata Success Value"
      SlackPostApprovalRequestReleaseSnsTopicName:
        default: "SNS Topic Name"
      CopyObjectOutputBucketName:
        default: "Destination Bucket Name"
      CopyObjectOutputFileName:
        default: "Destination Bucket Name"
      CopyObjectSourceBucketName:
        default: "Source Bucket Name"
      CopyObjectSourceSourceFileName:
        default: "Source File Name"
      SlackPostApprovalRequestFinalSnsTopicName:
        default: "SNS Topic Name"

Resources:
  LambdaZipsBucket:
    Type: AWS::S3::Bucket
