version: "2.1"
services:
  serverless:
    image: amaysim/serverless:1.60.0
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
    env_file:
      - .env
    command: bash -c "yarn installAllDeps && bash"
    volumes:
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
      - .:/opt/app
