service: ${self:custom.appname}-cpa
package:
  individually: true

frameworkVersion: '>=1.1.0 <2.0.0'

custom: '${file(serverless.vars.yml):vars}'
provider:
  name: aws
  runtime: ${self:custom.runtime.${self:provider.stage}}
  memorySize: ${self:custom.memory_size.${self:provider.stage}}
  stage: ${opt:stage}
  region: ${self:custom.region.${self:provider.stage}}
  environment: ${file(serverless.vars.yml):vars.common_env_vars}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:logs'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'log-group:/aws/lambda/*:*:*'
resources:
  - ${file(serverless.custom.yml):customResources}
  - ${file(serverless.custom.yml):customOutputs}
functions: ${file(serverless.functions.yml):functions}
