service: ${self:custom.appname}-cpa-layers
package:
  individually: true

frameworkVersion: '>=1.1.0 <2.0.0'

custom: '${file(../serverless.vars.yml):vars}'
provider:
  name: aws
  runtime: ${self:custom.runtime}
  memorySize: ${self:custom.memory_size.${self:provider.stage}}
  stage: ${opt:stage}
  region: ${env:AWS_REGION}
layers: ${self:custom.layers.${self:provider.stage}}
