#!/bin/bash
delete_bucket() {
    bucket_name=$1
    aws s3api delete-bucket --bucket $bucket_name \
        --region $AWS_REGION
    if [[ $? -eq 0 ]]; then
        echo "Successfully deleted the bucket: $bucket_name"
    fi
}

delete_buckets () {
    local filter=${1}
    buckets_list=$(aws s3api list-buckets)
    arr_string=$(echo "${buckets_list}" | jq --arg str "${filter}" -cr '.Buckets[] | select (.Name|test($str)) | .Name' | tr ' ' '\n')
    arr=($(echo $arr_string))
    # Returns the first options that it found
    for bucket_name in "${arr[@]}"; do
        delete_bucket $bucket_name
    done
}

delete_buckets "${APP_NAME}-cpa-deployment-[a-z0-9]*-${STAGE}"
delete_buckets "${APP_NAME}-cpa-layers-deployment-[a-z0-9]*-${STAGE}"
delete_buckets "${APP_NAME}-candidates-[a-z0-9]*-${STAGE}"
delete_buckets "${APP_NAME}-cfn-deployment-[a-z0-9]*-${STAGE}"
