#!/bin/bash
ROOTDIR="${PWD}"
servicesFolders=$(find ./services -maxdepth 1 -type d -exec bash -c '[ -f "$0"/package.json ] && [ -f "$0"/yarn.lock ]' '{}' \; -print | sort)
echo "Installing dependencies for the following services:" ; echo "$servicesFolders"
for folder in ${servicesFolders}; do cd $folder; echo ">> Installing deps of $folder"; yarn install ; cd "${ROOTDIR}"; done