#!/bin/bash
source ./scripts/packonly
echo "Deploying to AWS..."

if [ ! -z $is_pipeline ]; then
    echo ">> Deploying CodePipeline ..."
elif [  ! -z $is_codebuild ]; then
    echo ">> Deploying CodeBuild ..."
    deploy=$(aws cloudformation deploy \
        --capabilities CAPABILITY_IAM \
        --region "${region}" \
        --template-file "${template_file_path}" \
        --stack-name "${app_name}-${service_name}-${stage}" \
    --parameter-overrides AppName=$app_name Stage=$stage GithubBranchName=$github_branch GithubRepo=$github_repo GithubOwner=$github_owner CandidatesBucketName=$src_bucket_name)
fi

echo $deploy