#!/bin/bash
# if .env doesn't exist, create it
if [[ ! -f '.env' ]]; then
    echo "Copying env to .env"
    cp env .env
    [[ -f '.env.' ]] && echo "Successfully copied" || echo "Failed to copy" && exit
else
    echo ".env exists"
fi