AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CodeBuild Template for aws-codepipeline-actions

Parameters:
  AppName:
    Type: String
  Stage:
    Type: String
    Description: Select the stage to deploy
    AllowedValues:
      - dev
      - staging
      - prod
    ConstraintDescription: Must be any of the available options
  GithubOwner:
    Type: String
    Description: 'Github repo owner'
  GithubRepo:
    Type: String
    Description: 'Github repo name'
  GithubBranchName:
    Description: 'GitHub branch name'
    Type: String
  MetadataBucketName:
    Type: String
  MetadataFileName:
    Type: String

Resources:
  CodeBuildMetadataRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: /service-role/
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource:
                  - !Sub 'arn:aws:s3:::${MetadataBucketName}/*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - '*'

  # Creates candidate_metadata.nfo
  CodeBuildMetadataFile:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub ${AppName}-cpa-CodeBuildMetadata-${Stage}
      ServiceRole: !GetAtt CodeBuildMetadataRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        # Linux container with node installed
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: 'aws/codebuild/standard:3.0'
        EnvironmentVariables:
          - Name: STAGE
            Value: !Ref Stage
          - Name: METADATA_BUCKET_NAME
            Value: !Ref MetadataBucketName
          - Name: METADATA_FILE_NAME
            Value: !Ref MetadataFileName
      Source:
        Auth:
          Type: OAUTH
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 12
              commands:
                - echo ">> Repo URL - ${CODEBUILD_SOURCE_REPO_URL}"
                - echo ">> Source ID (PR or CommitId) - ${CODEBUILD_RESOLVED_SOURCE_VERSION}"
                - echo ">> Webhook Actor Account ID - ${CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID}"
                - echo ">> Webhook Head Ref - ${CODEBUILD_WEBHOOK_HEAD_REF}"
                - echo ">> Webhook Base Ref - ${CODEBUILD_WEBHOOK_BASE_REF}"
                - echo ">> Webhook Event - ${CODEBUILD_WEBHOOK_EVENT}"
                - echo ">> Webhook Trigger - ${CODEBUILD_WEBHOOK_TRIGGER}"
                - echo ">> Creating ${METADATA_FILE_NAME} locally"
                - touch ${METADATA_FILE_NAME}
            build:
              commands:
                - echo ">> Copying ${METADATA_FILE_NAME} to the bucket ${METADATA_BUCKET_NAME}"
                - aws s3 cp ${METADATA_FILE_NAME} s3://${METADATA_BUCKET_NAME}/${METADATA_FILE_NAME} --metadata source_id=${CODEBUILD_RESOLVED_SOURCE_VERSION},webhook_base_ref=${CODEBUILD_WEBHOOK_BASE_REF},webhook_head_ref=${CODEBUILD_WEBHOOK_HEAD_REF},webhook_event=${CODEBUILD_WEBHOOK_EVENT},webhook_actor=${CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID},webhook_trigger=${CODEBUILD_WEBHOOK_TRIGGER},repo_url=${CODEBUILD_SOURCE_REPO_URL}
        GitCloneDepth: 1
        Location: !Sub 'https://github.com/${GithubOwner}/${GithubRepo}'
        ReportBuildStatus: true
        Type: GITHUB
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED, PULL_REQUEST_MERGED
            - Type: BASE_REF
              Pattern: !Sub 'refs/heads/${GithubBranchName}$'
              ExcludeMatchedPattern: false
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub '^refs/heads/${GithubBranchName}$'
            - Type: FILE_PATH
              Pattern: README.md
              ExcludeMatchedPattern: true
